language: node_js

node_js:
  - "8"
  - "10"

install:
  - npm i

script:
  - npm run test

after_success:
  - npm run coverage
  - npm run build

jobs:
  include:
    - stage: npm release
      node_js: 10
      script: echo "deploying to npm"
      deploy:
        provider: npm
        email: $NPM_AUTHOR_EMAIL
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true